export const MODELSAI = [
    { id: 'gpt-4o-mini', name: 'GPT-4 Mini' },
    { id: 'gpt-4', name: 'GPT-4' },
    { id: 'mixtral-8x7b', name: 'Mixtral 8x7B' },
    { id: 'claude-3-haiku', name: 'Claude 3 Haiku' },
    { id: 'llama-3.1-70b', name: 'Llama 3 70B' }
];

export const REGIONS = [
    { value: '', name: 'All Regions' },
    { value: 'ar-es', name: 'Argentina' },
    { value: 'au-en', name: 'Australia' },
    { value: 'at-de', name: 'Austria' },
    { value: 'be-fr', name: 'Belgium (fr)' },
    { value: 'be-nl', name: 'Belgium (nl)' },
    { value: 'br-pt', name: 'Brazil' },
    { value: 'bg-bg', name: 'Bulgaria' },
    { value: 'ca-en', name: 'Canada (en)' },
    { value: 'ca-fr', name: 'Canada (fr)' },
    { value: 'ct-ca', name: 'Catalonia' },
    { value: 'cl-es', name: 'Chile' },
    { value: 'cn-zh', name: 'China' },
    { value: 'co-es', name: 'Colombia' },
    { value: 'hr-hr', name: 'Croatia' },
    { value: 'cz-cs', name: 'Czech Republic' },
    { value: 'dk-da', name: 'Denmark' },
    { value: 'ee-et', name: 'Estonia' },
    { value: 'fi-fi', name: 'Finland' },
    { value: 'fr-fr', name: 'France' },
    { value: 'de-de', name: 'Germany' },
    { value: 'gr-el', name: 'Greece' },
    { value: 'hk-tzh', name: 'Hong Kong' },
    { value: 'hu-hu', name: 'Hungary' },
    { value: 'is-is', name: 'Iceland' },
    { value: 'in-en', name: 'India (en)' },
    { value: 'id-en', name: 'Indonesia (en)' },
    { value: 'ie-en', name: 'Ireland' },
    { value: 'il-en', name: 'Israel (en)' },
    { value: 'it-it', name: 'Italy' },
    { value: 'jp-jp', name: 'Japan' },
    { value: 'kr-kr', name: 'Korea' },
    { value: 'lv-lv', name: 'Latvia' },
    { value: 'lt-lt', name: 'Lithuania' },
    { value: 'my-en', name: 'Malaysia (en)' },
    { value: 'mx-es', name: 'Mexico' },
    { value: 'nl-nl', name: 'Netherlands' },
    { value: 'nz-en', name: 'New Zealand' },
    { value: 'no-no', name: 'Norway' },
    { value: 'pk-en', name: 'Pakistan (en)' },
    { value: 'pe-es', name: 'Peru' },
    { value: 'ph-en', name: 'Philippines (en)' },
    { value: 'pl-pl', name: 'Poland' },
    { value: 'pt-pt', name: 'Portugal' },
    { value: 'ro-ro', name: 'Romania' },
    { value: 'ru-ru', name: 'Russia' },
    { value: 'xa-ar', name: 'Saudi Arabia' },
    { value: 'sg-en', name: 'Singapore' },
    { value: 'sk-sk', name: 'Slovakia' },
    { value: 'sl-sl', name: 'Slovenia' },
    { value: 'za-en', name: 'South Africa' },
    { value: 'es-ca', name: 'Spain (ca)' },
    { value: 'es-es', name: 'Spain (es)' },
    { value: 'se-sv', name: 'Sweden' },
    { value: 'ch-de', name: 'Switzerland (de)' },
    { value: 'ch-fr', name: 'Switzerland (fr)' },
    { value: 'tw-tzh', name: 'Taiwan' },
    { value: 'th-en', name: 'Thailand (en)' },
    { value: 'tr-tr', name: 'Turkey' },
    { value: 'us-en', name: 'US (English)' },
    { value: 'us-es', name: 'US (Spanish)' },
    { value: 'ua-uk', name: 'Ukraine' },
    { value: 'uk-en', name: 'United Kingdom' },
    { value: 'vn-en', name: 'Vietnam (en)' }
];

export const TIMES = [
    { value: '', name: 'Any Time' },
    { value: 'd', name: 'Past Day' },
    { value: 'w', name: 'Past Week' },
    { value: 'm', name: 'Past Month' },
    { value: 'y', name: 'Past Year' }
];

export const MODELSIMAGE = [
    { id: 'sdxl', name: 'SDXL' },
    { id: 'sd-3', name: 'Stable Diffusion 3' },
    { id: 'playground-v2.5', name: 'Playground v2.5' },
    { id: 'flux-realism', name: 'Flux Realism' }
  ];